-- MySQL Script generated by MySQL Workbench
-- Tue Mar 12 11:14:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema G_bibliotheque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema G_bibliotheque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `G_bibliotheque` DEFAULT CHARACTER SET utf8 ;
USE `G_bibliotheque` ;

-- -----------------------------------------------------
-- Table `G_bibliotheque`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `G_bibliotheque`.`Admin` ;

CREATE TABLE IF NOT EXISTS `G_bibliotheque`.`Admin` (
  `id_Admin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pas active',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_Admin`));


-- -----------------------------------------------------
-- Table `G_bibliotheque`.`Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `G_bibliotheque`.`Manager` ;

CREATE TABLE IF NOT EXISTS `G_bibliotheque`.`Manager` (
  `id_Manager` INT NOT NULL AUTO_INCREMENT,
  `id_Admin` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pas active',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_Manager`),
  CONSTRAINT `admin__manager`
    FOREIGN KEY (`id_Admin`)
    REFERENCES `G_bibliotheque`.`Admin` (`id_Admin`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `G_bibliotheque`.`ObjectType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `G_bibliotheque`.`ObjectType` ;

CREATE TABLE IF NOT EXISTS `G_bibliotheque`.`ObjectType` (
  `id_ObjectType` INT NOT NULL AUTO_INCREMENT,
  `id_Admin` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_ObjectType`),
  CONSTRAINT `admin__objecttype`
    FOREIGN KEY (`id_Admin`)
    REFERENCES `G_bibliotheque`.`Admin` (`id_Admin`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G_bibliotheque`.`Object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `G_bibliotheque`.`Object` ;

CREATE TABLE IF NOT EXISTS `G_bibliotheque`.`Object` (
  `id_Object` INT NOT NULL AUTO_INCREMENT,
  `id_Admin` INT NOT NULL,
  `id_ObjectType` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `emprunt_duration` INT NOT NULL DEFAULT 3,
  `emprunted` VARCHAR(255) NOT NULL DEFAULT 'Disponible',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_Object`),
  CONSTRAINT `admin__object`
    FOREIGN KEY (`id_Admin`)
    REFERENCES `G_bibliotheque`.`Admin` (`id_Admin`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `objecttype__object`
    FOREIGN KEY (`id_ObjectType`)
    REFERENCES `G_bibliotheque`.`ObjectType` (`id_ObjectType`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G_bibliotheque`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `G_bibliotheque`.`User` ;

CREATE TABLE IF NOT EXISTS `G_bibliotheque`.`User` (
  `id_User` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pas active',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_User`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G_bibliotheque`.`Emprunt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `G_bibliotheque`.`Emprunt` ;

CREATE TABLE IF NOT EXISTS `G_bibliotheque`.`Emprunt` (
  `id_Emprunt` INT NOT NULL AUTO_INCREMENT,
  `id_User` INT NOT NULL,
  `id_Object` INT NOT NULL,
  `Status` VARCHAR(255) NOT NULL DEFAULT 'En cours de traiter',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_Emprunt`),
  CONSTRAINT `object__emprunt`
    FOREIGN KEY (`id_Object`)
    REFERENCES `G_bibliotheque`.`Object` (`id_Object`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user__emprint`
    FOREIGN KEY (`id_User`)
    REFERENCES `G_bibliotheque`.`User` (`id_User`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
